# Generated by Django 3.1.7 on 2021-02-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=254)),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('location', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('is_liked', models.BooleanField(default=False)),
            ],
        ),
    ]
